spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_reservation
    username: admin
    password: admin
  application:
    name: flight_reservation
